//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public cart()
        {
            this.cart_item = new HashSet<cart_item>();
        }
    
        public int id { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> submit_date { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> payment_gtw { get; set; }
        public Nullable<System.DateTime> last_update { get; set; }
        public Nullable<int> customer_id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual customer customer { get; set; }
        public virtual ICollection<cart_item> cart_item { get; set; }
    }
}
